//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesPlane
    {
        public int IdClientesPlanes { get; set; }
        public Nullable<int> IdClientes { get; set; }
        public Nullable<int> IdPlanes { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Plane Plane { get; set; }
    }
}
