//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ClientesPlanes = new HashSet<ClientesPlane>();
        }
    
        public int IdClientes { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ICollection<ClientesPlane> ClientesPlanes { get; set; }
    }
}
