//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public Plane()
        {
            this.ClientesPlanes = new HashSet<ClientesPlane>();
            this.CoberturasPlanes = new HashSet<CoberturasPlane>();
            this.PlanesCoberturas = new HashSet<PlanesCobertura>();
        }
    
        public int IdPlanes { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ICollection<ClientesPlane> ClientesPlanes { get; set; }
        public virtual ICollection<CoberturasPlane> CoberturasPlanes { get; set; }
        public virtual ICollection<PlanesCobertura> PlanesCoberturas { get; set; }
    }
}
